language: java

jdk:
  -openjdk15

os:
  - linux
  - osx
  - windows

before_install:
- |-
    case $TRAVIS_OS_NAME in
      linux)
  		chmod +x gradlew
		;;
	esac
- |-
    case $TRAVIS_OS_NAME in
      windows)
		choco install openjdk
		;;
	esac
